project:
  type: website

website:
  favicon: Robot_face_amico.png
  page-navigation: true # внизу страницы появляются стрелки с переходом на след\пред статью внутри секции
  search: 
    location: navbar # место панели поиска
    type: textbox # тип
    copy-button: true # кнопка копии адреса найденой статьи
    
  open-graph: true # подключение разметки Open Graph
  
  # настройка верхнего меню
  navbar: 
    left:
      - text: "Home"
        file: index.qmd
 
      - text: " R "
        file: r_language/r_language_page.qmd

      - text: "Visualization"
        file: visualization/visualization_page.qmd
      
# настройка бокового меню
# чтобы боковое меню появлялось только на определенных страницах нужно связать заголовки в верхнем и боковом меню
# а также чтобы файл в верхнем меню был такой же как первый файл после заголовка в боковом
  sidebar:
      
    - title: "R"
      contents:
        - r_language/r_language_page.qmd
        - section: "Tidyverse"
          contents: 
            - r_language/Tidyverse/tibble_tidyverse.qmd
            - r_language/Tidyverse/dplyr_tidyverse.qmd
            
        - text: "---"
        - section: "Tutorial"
          contents: 
            - r_language/Tutorial/Quarto_cheatsheet.qmd

        
    - title: "Visualization"
      contents:
        - visualization/visualization_page.qmd
        - text: "---"
        - section: "Diagramms"
          contents:
            - section: "UpSet"
              contents: visualization/Diagramms/Upset/*.qmd
    
  # настройка нижнего колонтитула         
  page-footer:
    left: "Copyright 2022-2023, Best Practices IT" 
    center: 
      - icon: github
        href: https://github.com/Azveg
      - icon: telegram
        href: https://t.me/best_practices_it


format:
  html:
    theme: 
      #dark: Cyborg # если первой указать тему dark, то оно  будет по умолчанию
      light: Journal
    highlight-style: github # стиль блоков кода
    code-link: true
    df-print: paged
    fig-cap-location: bottom
      
    css: styles.css
    toc: true # вывод содержания страницы (выводятся заголовки до 3го уровня)